version: "3.9"
services:
  api:
    build: 
      dockerfile: Dockerfile_test
      context: .
    volumes:
      - .:/code
    # expose:
    #   - 8000
    ports:
      - 80:8000
    env_file:
      - .env_dev
    stdin_open: true
    tty: true
    depends_on:
      - redis_cache
    
  db:
    build:
      dockerfile: Dockerfile_db
      context: .
    ports:
      - 8001:5432
    env_file:
      - .env_dev
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis_cache:
    image: redis:7.0.0
    entrypoint: ["bash", "-c", "redis-server", "--daemonize", "yes"]
    ports:
      - 6379:6379
    depends_on:
      - db

  # nginx:
  #   build: ./nginx
  #   ports:
  #     - 1337:80
  #   depends_on:
  #     - api

volumes:
  pgdata: